{
 "title": "21",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "I/O now",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_disk_io_now", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "Memory ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes  - node_memory_MemFree_bytes",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without(cpu)(irate(node_cpu_seconds_total{mode!=\"idle\"}[1m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Used Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes -  node_filesystem_avail_bytes",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}